import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  
  title: "Academics-Pro",
  description: "Generated by create next app",
 
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
 
      </head>
      <body
        className={`bg-background text-foreground antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
